repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=4096"]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        files: \.(js|rb|md|py|sh|txt|yaml|yml|kidm)$

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        language: system
        entry: uvx ruff check --fix
        types_or: [ python, pyi ]
      - id: ruff-format
        name: ruff format
        language: system
        entry: uvx ruff format
        types_or: [ python, pyi ]
      - id: ty
        name: ty check
        language: system
        entry: uvx ty check
        types_or: [ python, pyi ]
        pass_filenames: false
