[project]
name = "trunx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.5.2",
    "polars>=1.38.1",
    "dotenv>=0.9.9",
    "icoscp-core>=0.3.11",
    "ipython>=9.10.0",
    "pre-commit>=4.2.0",
    "requests>=2.32.5",
    "ruff>=0.11.10",
    "jax>=0.9.0.1",
    "haversine>=2.9.0",
    "fastexcel>=0.19.0",
    "rpy2>=3.6.5",
    "seaborn>=0.13.2",
    "optax>=0.2.8",
    "pyarrow>=23.0.1",
    "pyreadr>=0.5.4",
    "openpyxl>=3.1.5",
    "salib>=1.5.2",
    "nbstripout>=0.9.1",
    "marimo>=0.23.6",
    "rasterio>=1.5.0",
    "lxml>=6.1.1",
    "docx>=0.2.4",
    "tqdm>=4.67.3",
]

# Set curent project as a package, with src/ folder.
[tool.uv]
package = true

# Set ruff and ty as only a local deps for development.
[dependency-groups]
dev = [
    "ruff>=0.11.10",
    "pre-commit>=4.2.0",
    "ty>=0.0.13",
    "pytest>=8.0.0",
    "responses>=0.25.0",
]

# Build backend
# -------------
[build-system]
requires = ["uv_build>=0.9.0,<0.9.26"]
build-backend = "uv_build"


# Linting rules
# -------------
# Longer than standard 79 char max line length.
[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # pydocstyle
    "D",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
extend-select = [
  "E501", # enforce the line-too-long rule
  "UP",  # pyupgrade
]

# Defines which linter errors to ignore.
[tool.ruff.lint.per-file-ignores]
"*/*" = [
  "E712", # Allow comparing to == True, since needed by polars.
  "UP015", # Allow explicit read-only mode in file open.
] 
"src/*" = ["D104", "D102", "D105", "F722", "F401"] 
# D10*: Allow empty docstrings in __init__.py. and in methods (including magic ones).
# F722: Allow forward type references (needed for jaxtyping)
# F401: allow unused import (needed for rioxarray)
"tests/*" = ["D"] # allow undocumented tests
"scripts/*" = ["D100", "D103"] # allow undocumented scripts

# Docstring style numpy (instead of Google).
[tool.ruff.lint.pydocstyle]
convention = "numpy"


# Type Checker Configuration
# --------------------------
[tool.ty.rules]
# Disable specific rules that are problematic for some packages.
unresolved-import = "ignore"

[tool.pyright]
venvPath = "."
venv = ".venv"
