"""HMC parameter estimation for 3PG model using DBH observations."""

import os
from typing import NamedTuple

import jax
import jax.numpy as jnp
import jax.random as random
import numpy as np
import numpyro
import numpyro.distributions as dist
import pandas as pd
import polars as pl
from numpyro.infer import MCMC, NUTS

from trunx.config import threepg_data_folder
from trunx.gp3.bayesiancalibrations.load_files import (
    PlotData,
    load_plot_data,
    load_plot_ids_from_file,
    load_priors_from_file,
)
from trunx.gp3.helper_function import is_dormant
from trunx.gp3.model_inputs import ClimateData, Params, SiteData, SpeciesData, State
from trunx.gp3.prepare_climate import prepare_climate
from trunx.gp3.prepare_site import prepare_site
from trunx.gp3.prepare_species import prepare_species
from trunx.gp3.run_3pg import run_3pg

cpu_count = os.cpu_count() or 1
numpyro.set_host_device_count(max(1, int(cpu_count)))


def multi_plot_model(
    plots: list[PlotData],
    fixed_params,
    priors: dict[str, tuple[float, float]] | None = None,
):
    """Bayesian model with shared physiology parameters estimated across multiple plots.

    Parameters are sampled once and then each plot contributes its own
    likelihood terms. Plots may differ in climate length, site, species
    composition, and available observations.

    Parameters
    ----------
    plots : list[PlotData]
        One PlotData per forest plot. All plots must share the same species
        set so that a single Params vector applies to all.
    fixed_params
        Non-estimated parameters (used as base for _replace).
    priors : dict[str, tuple[float, float]] | None
        Parameter names → (min, max) uniform prior bounds.
        If None, uses the same defaults as the single-plot model.
    """
    if priors is None:
        raise ValueError("Priors must be provided for plot analysis")
    # --- Sample shared physiology parameters once ---
    param_samples = {
        name: numpyro.sample(name, dist.Uniform(lo, hi)) for name, (lo, hi) in priors.items()
    }
    params = fixed_params._replace(**param_samples)

    # --- Per-plot likelihood contributions ---
    # Sigma is sampled per (plot × variable): measurement noise can differ
    # between plots due to different campaigns, instruments, or observers.

    for i, plot in enumerate(plots):
        _, outputs = run_3pg(plot.initial_state, plot.climate, params, plot.site, plot.species)
        for var_name, (obs_times, obs_values) in plot.observations.items():
            if var_name not in outputs:
                continue
            pred_values = outputs[var_name][obs_times]  # (n_obs, n_species)
            sigma = numpyro.sample(f"sigma_{var_name}_plot{i}", dist.HalfNormal(1.0))
            numpyro.sample(
                f"obs_{var_name}_plot{i}",
                dist.StudentT(df=3, loc=pred_values, scale=sigma),
                obs=obs_values,
            )


def run_multi_plot_analysis(
    params_file: str,
    plot_files: list[tuple[str, str]],
    param_names: list[str] | None = None,
    num_warmup: int = 1000,
    num_samples: int = 1000,
    num_chains: int = 4,
    seed: int = 42,
) -> tuple[MCMC, dict]:
    """Run HMC inference with shared parameters estimated across multiple plots.

    Parameters
    ----------
    params_file : str
        Excel file with ``parameters`` and ``param_bound`` sheets — shared across
        all plots. Does **not** need site/climate/observed sheets.
    plot_files : list[tuple[str, str]]
        List of ``(file_path, plot_id)`` pairs — one entry per forest plot.
        ``file_path`` must point to a nested parquet file generated by
        ``prepare_multiplots_data.py``.
    param_names : list[str] | None
        Parameters to estimate. If None, all parameters with both min and
        max values in ``param_bound`` are optimized.
    num_warmup : int
        Number of HMC warmup steps.
    num_samples : int
        Number of posterior samples per chain.
    num_chains : int
        Number of independent MCMC chains.
    seed : int
        Random seed.

    Returns
    -------
    MCMC
        NumPyro MCMC object containing all chains.
    dict
        Posterior samples dictionary.
    """
    # Load priors from the shared params file
    priors = load_priors_from_file(params_file, param_names)

    if len(plot_files) == 0:
        raise ValueError("plot_files must contain at least one (file_path, plot_id) entry")

    plots: list[PlotData] = []
    fixed_params = None

    for file_path, plot_id in plot_files:
        plot, fp = load_plot_data(file_path, plot_id, params_file)
        plots.append(plot)
        if fixed_params is None:
            fixed_params = fp

    # Sanity checks: all plots must share the same species.
    species_ref = tuple(plots[0].species.specie)
    for plot in plots[1:]:
        if tuple(plot.species.specie) != species_ref:
            got_species = tuple(plot.species.specie)
            raise ValueError(
                "All plots in one multi-plot run must share the same species set and order. "
                f"Expected {species_ref}, got {got_species} for plot {plot.plot_id}."
            )
    # Check that all plots have observations for fitting.
    empty_obs_plots = [plot.plot_id for plot in plots if len(plot.observations) == 0]
    if empty_obs_plots:
        raise ValueError(
            "All plots must contain observations for fitting. "
            f"Plots without observations: {empty_obs_plots}"
        )

    rng_key = random.PRNGKey(seed)
    _, subkey = random.split(rng_key)

    kernel = NUTS(
        multi_plot_model,
        target_accept_prob=0.9,
        max_tree_depth=10,
    )
    mcmc = MCMC(
        kernel,
        num_warmup=num_warmup,
        num_samples=num_samples,
        num_chains=num_chains,
        progress_bar=True,
    )
    mcmc.run(subkey, plots, fixed_params, priors)

    samples = mcmc.get_samples()
    mcmc.print_summary()
    return mcmc, samples


def run_multi_plot_analysis_for_file(
    plot_file: str,
    params_file: str,
    param_names: list[str] | None = None,
    num_warmup: int = 200,
    num_samples: int = 200,
    num_chains: int = 2,
    seed: int = 42,
) -> tuple[MCMC, dict]:
    """Run shared-parameter inference across all plots in one parquet file."""
    plot_ids = load_plot_ids_from_file(plot_file)[0:1]
    plot_files = [(plot_file, plot_id) for plot_id in plot_ids]
    print(f"Running shared-parameter optimization across all plots: {plot_ids}")
    return run_multi_plot_analysis(
        params_file=params_file,
        plot_files=plot_files,
        param_names=param_names,
        num_warmup=num_warmup,
        num_samples=num_samples,
        num_chains=num_chains,
        seed=seed,
    )


if __name__ == "__main__":
    # Example parquet-based multi-plot analysis across one species file.
    species = "Picea_abies"
    run_multi_plot_analysis_for_file(
        plot_file=os.path.join(threepg_data_folder, "icp_plot_data_" + species + ".parquet"),
        params_file=os.path.join(threepg_data_folder, "params_bounds.parquet"),
        param_names=None,
    )
