# ruff: noqa: E501
"""Marimo table of Long-term Forest Ecosystem Research site metadata."""

import marimo

__generated_with = "0.24.0"
app = marimo.App(width="full")


@app.cell
def _():
    import marimo as mo
    import pandas as pd

    return mo, pd


@app.cell
def _(pd):
    # WSL LWF site descriptors; DEIMS-SDR representative coordinates.
    # Plot area is the WSL value. "n.d." is kept as missing.
    # Species_listing is only a classification of species explicitly listed
    # on the WSL page, not a complete stand inventory.
    sites = pd.DataFrame(
        [
            [
                "ALP",
                "Alptal",
                "Alpthal",
                "SZ",
                47.0486366,
                8.7125782,
                1149,
                1160,
                1170,
                0.60,
                23,
                "Picea abies",
                "Single main species listed",
                "Picea abies 180–230 yr",
                "Northern Pennsylvanian; Upper Cretaceous–Lower Eocene, Wägital flysch",
                "Mollic Gleysols; Gleyic Cambisols",
                "49: Equiseto-Abietetum",
                "high forest",
                "selection",
                39.3,
                321,
                2011,
                "31 May 1995",
            ],
            [
                "BEA",
                "Beatenberg",
                "Beatenberg",
                "BE",
                46.7003438,
                7.7623374,
                1490,
                1511,
                1532,
                2.00,
                66,
                "Picea abies",
                "Single main species listed",
                "Picea abies 190–210 yr",
                "Helvetic, Tertiary, Eocene; Hohgan sandstone",
                "Gleyic Podzols",
                "57: Sphagno-Piceetum calamagrostietosum villosae",
                "high forest",
                "selection",
                46.4,
                851,
                2011,
                "25 September 1996",
            ],
            [
                "BET",
                "Bettlachstock",
                "Bettlachstock",
                "SO",
                47.2251551,
                7.4166536,
                1101,
                1150,
                1196,
                1.28,
                66,
                "Fagus sylvatica",
                "Multiple species listed",
                "Fagus sylvatica 170–190 yr; Picea abies 200 yr; Fraxinus excelsior 170 yr; Ulmus glabra 160 yr; Abies alba 190 yr",
                "Chain Jurassic; Jurassic: Dogger, upper main roe stone",
                "Rendzic Leptosols; Calcaric Cambisols",
                "13 h: Cardamino-Fagetum tilietosum",
                "high forest",
                "forest reserve",
                49.5,
                632,
                2011,
                "6 June 1995",
            ],
            [
                "CEL",
                "Celerina",
                "Celerina",
                "GR",
                46.4921451,
                9.8888024,
                1846,
                1871,
                1896,
                2.00,
                34,
                "Pinus cembra",
                "Single main species listed",
                "Pinus cembra uneven-aged; 210–250 yr",
                "Subsoil: eastern alpine; pre-Triadic deep rocks. Surface: Quaternary; carbonate-free moraine",
                "Podzol; brown earth",
                "59: Larici-Pinetum cembrae",
                "high forest",
                "group selection",
                48.6,
                469,
                2011,
                "3 July 1996",
            ],
            [
                "CHI",
                "Chironico",
                "Chironico",
                "TI",
                46.4468172,
                8.8121720,
                1342,
                1370,
                1387,
                2.00,
                35,
                "Picea abies",
                "Multiple species listed",
                "Picea abies 160–180 yr; Abies alba 140–160 yr",
                "Subsoil: Penninic; paragneiss and mica schist. Surface: Quaternary; carbonate-free moraine, hanging debris",
                "Distric Cambisol",
                "47: Calamagrostio villosae-Abietetum",
                "high forest",
                "group selection",
                54.1,
                750,
                2011,
                "29 August 1995",
            ],
            [
                "DAV",
                "Davos",
                "Davos",
                "GR",
                46.8153458,
                9.8552112,
                1635,
                1650,
                1665,
                0.60,
                35,
                "Picea abies",
                "Single main species listed",
                "Picea abies 200–390 yr",
                "Landslide material from paraglacial stones of the Silvretta cover",
                "Podzol; brown earth; regosol",
                "58: Larici-Piceetum",
                "high forest",
                "group selection",
                47.0,
                498,
                2006,
                "15 June 2006",
            ],
            [
                "ISO",
                "Isone",
                "Isone",
                "TI",
                46.1248982,
                9.0080555,
                1181,
                1220,
                1259,
                2.00,
                58,
                "Fagus sylvatica",
                "Single main species listed",
                "Fagus sylvatica uneven-aged; 70–85–100 yr",
                "Subsoil: Southern Alpine, pre-Permian basement, Ceneri zone; slaty biotite plagioclase gneiss. Surface: Quaternary; moraine, hanging debris",
                "Humic Cambisol",
                "4: Luzulo niveae-Fagetum dryopteridetosum",
                "former coppice",
                "unmanaged",
                37.4,
                1254,
                2011,
                "5 September 1995",
            ],
            [
                "JUS",
                "Jussy",
                "Jussy",
                "GE",
                46.2298528,
                6.2908547,
                496,
                501,
                506,
                1.99,
                3,
                "Quercus species",
                "Multiple species listed",
                "Carpinus betulus 60 yr; Populus tremula 60 yr; Quercus petrea 90 yr",
                "Quaternary; clay-rich Würmian ground moraine",
                "Stagnic Luvisols",
                "35: Galio silvatici-Carpinetum",
                "former coppices with standards",
                "unmanaged / group selection",
                36.6,
                1278,
                2011,
                "31 May 1995",
            ],
            [
                "LAE",
                "Lägeren",
                "Wettingen",
                "AG",
                47.4783000,
                8.3643900,
                643,
                680.5,
                718,
                1.34,
                37,
                "Fagus sylvatica",
                "Multiple species listed",
                "Picea abies 120–170 yr; Fagus sylvatica ca. 150 yr",
                "Chain Jurassic; Jurassic: Malm, Molasseehan Clay",
                "calcareous brown soil; chromic luvisol; mixed rendzina",
                "Galio odoratio-Fagetum typicum bis Pulmonario-Fagetum typicum",
                "high forest",
                "forest reserve",
                72.18,
                503,
                2011,
                "1 May 2012",
            ],
            [
                "LAN",
                "Lantsch",
                "Lantsch",
                "GR",
                46.6980544,
                9.5646678,
                1458,
                1470,
                1490,
                None,
                16,
                "Picea abies",
                "Single main species listed",
                None,
                "Eastern Alpine. Suspended debris of Mesozoic shales, dolomites and limestones",
                None,
                "65: Erico-Pinetum silvestris",
                "high forest",
                None,
                40.1,
                709,
                2011,
                "15 September 1997",
            ],
            [
                "LAU",
                "Lausanne",
                "Lausanne",
                "VD",
                46.5837664,
                6.6580421,
                800,
                807,
                814,
                2.00,
                7,
                "Fagus sylvatica",
                "Multiple species listed",
                "Abies alba 160–170 yr; Picea abies 160–170 yr; Fagus sylvatica 160–170 yr",
                "Subsoil: Tertiary, Miocene, Burdigalian, upper marine molasse; sandstone. Surface: Quaternary, Würm; Würm-glacial moraine",
                "Distric Cambisols",
                "8: Milio-Fagetum",
                "high forest",
                "group selection",
                59.9,
                650,
                2011,
                "5 September 1994",
            ],
            [
                "LEN",
                "Lens",
                "Lens",
                "VS",
                46.2685558,
                7.4359392,
                1033,
                1063,
                1093,
                2.00,
                75,
                "Pinus sylvestris",
                "Single main species listed",
                "150–170 yr",
                "Subsoil: Penninic, Ferret zone, Triassic; sandy limestone. Surface: hanging rubble",
                "Calcaric Cambisol",
                "≈64: Cytiso-Pinetum silvestris",
                "high forest",
                "unmanaged",
                31.8,
                2304,
                2011,
                "15 March 1996",
            ],
            [
                "NAT",
                "Nationalpark",
                "Zernez",
                "GR",
                46.6625010,
                10.2300874,
                1890,
                1900,
                1907,
                2.00,
                11,
                "Pinus mugo",
                "Single main species listed",
                "Pinus mugo 210 yr",
                "Post-glacial alluvial fan; calcareous moraine, dolomites, limestones, clay shales, roughwackes",
                "Rendzic Leptosol",
                "67: Erico-Pinetum montanae",
                "high forest",
                "forest reserve",
                23.7,
                2450,
                2011,
                "10 October 1995",
            ],
            [
                "NEU",
                "Neunkirch",
                "Neunkirch",
                "SH",
                47.6837031,
                8.5356830,
                554,
                581,
                609,
                2.00,
                58,
                "Fagus sylvatica",
                "Multiple species listed",
                "Fagus sylvatica 160 yr; Acer pseudoplatanus 160 yr; Tilia sp. 110 yr",
                "Tabular Jurassic, upper Malm limestone; Malm hanging debris",
                "Rendzic Leptosols",
                "13: Cardamino-Fagetum tilietosum",
                "former coppices with standards",
                "reserve",
                56.5,
                442,
                2011,
                "14 July 1995",
            ],
            [
                "NOV",
                "Novaggio",
                "Novaggio",
                "TI",
                46.0226119,
                8.8341613,
                902,
                949,
                997,
                1.50,
                68,
                "Quercus cerris",
                "Multiple species listed",
                "Castanea sativa 90 yr; Betula pendula 70 yr; Quercus cerris 70 yr",
                "Subsoil: Southern Alpine, pre-Permian basement; orthogneiss, schistose biotite plagioclase gneiss. Surface: Quaternary; carbonate-free Würmian moraine",
                "Kryptopodzole",
                "42: Phyteumo betonicifoliae-Quercetum castanosum",
                "former coppice",
                "unmanaged",
                27.0,
                1130,
                2011,
                "8 March 1995",
            ],
            [
                "OTH",
                "Othmarsingen",
                "Othmarsingen",
                "AG",
                47.3995354,
                8.2267566,
                467,
                483.5,
                500,
                1.00,
                27,
                "Fagus sylvatica",
                "Multiple species listed",
                "Fagus sylvatica 120–140 yr; Tilia sp. 120–140 yr",
                "Subsoil: Miocene, Burdigalian, upper marine molasse; sandstone. Surface: Quaternary, calcareous Würm glacial moraine",
                "Stagnic Luvisols; Haplic Luvisols",
                "7: Galio odorati-Fagetum typicum",
                "former coppices with standards",
                "group selection",
                62.8,
                167,
                2011,
                "9 September 1994",
            ],
            [
                "SCH",
                "Schänis",
                "Schänis",
                "SG",
                47.1650464,
                9.0670726,
                693,
                713,
                773,
                2.00,
                60,
                "Fagus sylvatica",
                "Multiple species listed",
                "Abies alba 130–150 yr; Fraxinus excelsior 130–150 yr; Fagus sylvatica 130–150 yr",
                "Tertiary. Subalpine Molasse, Oligocene, Chattian, Kalknagelfluh",
                "pseudo-overgleyed brown earth",
                "13: Cardamino-Fagetum tilietosum",
                "high forest",
                "group selection",
                55.8,
                611,
                2011,
                "17 September 1997",
            ],
            [
                "VIS",
                "Visp",
                "Visp",
                "VS",
                46.2968789,
                7.8583245,
                657,
                695,
                733,
                2.00,
                80,
                "Pinus sylvestris",
                "Single main species listed",
                "Pinus sylvestris uneven-aged; 40–80 yr",
                "Penninic, Jurassic, Graubünden schist; calcareous phyllites, hanging debris",
                "Calcaric Cambisol",
                "≈38: Arabidi turritae-Quercetum pubescentis",
                "high forest",
                "unmanaged",
                53.9,
                650,
                2011,
                "13 March 1996",
            ],
            [
                "VOR",
                "Vordemwald",
                "Vordemwald",
                "AG",
                47.2740627,
                7.8867633,
                473,
                480,
                487,
                2.00,
                14,
                "Abies alba",
                "Multiple species listed",
                "Abies alba 110 yr; Quercus sp. 190–210 yr",
                "Subsoil: Oligocene, Aquitanian, lower freshwater molasse, variegated marl. Surface: fissure-bottom moraine",
                "Distric Gleysols",
                "46: Bazzanio-Abietetum",
                "high forest",
                "group selection",
                53.9,
                1084,
                2011,
                "18 August 1995",
            ],
        ],
        columns=[
            "LWF_ID",
            "Site",
            "Community",
            "Canton",
            "Latitude",
            "Longitude",
            "Altitude_min_m",
            "Altitude_mean_m",
            "Altitude_max_m",
            "Plot_area_ha",
            "Mean_slope_pct",
            "Main_tree_species",
            "Species_listing",
            "Maximum_tree_age",
            "Geology",
            "Soil_type",
            "Woodland_association",
            "Management_system",
            "Silvicultural_system",
            "Top_height_diameter_cm",
            "Trees_BHD_ge_12cm",
            "Tree_count_reference_year",
            "Installation_date",
        ],
    )
    return (sites,)


@app.cell
def _(mo, sites):
    sources = {
        "WSL LWF sites": "https://lwf.wsl.ch/en/flaechen",
        "DEIMS-SDR search": "https://deims.org/search-sites",
    }

    site_labels = {row.LWF_ID: f"{row.LWF_ID} — {row.Site}" for row in sites.itertuples()}

    site_selector = mo.ui.dropdown(
        options={"All 19 sites": "All", **{v: k for k, v in site_labels.items()}},
        value="All 19 sites",
        label="Site",
    )
    return site_selector, sources


@app.cell
def _(mo, site_selector, sites, sources):
    selected_id = site_selector.value

    if selected_id == "All":
        table = sites.copy()
    else:
        table = sites.loc[sites["LWF_ID"] == selected_id].copy()

    # Friendly column names for the displayed table.
    table = table.rename(
        columns={
            "LWF_ID": "LWF ID",
            "Site": "Site name",
            "Community": "Community",
            "Canton": "Canton",
            "Latitude": "Latitude (°)",
            "Longitude": "Longitude (°)",
            "Altitude_min_m": "Altitude min (m)",
            "Altitude_mean_m": "Altitude mean (m)",
            "Altitude_max_m": "Altitude max (m)",
            "Plot_area_ha": "Plot area (ha)",
            "Mean_slope_pct": "Mean slope (%)",
            "Main_tree_species": "Main tree species",
            "Species_listing": "Species listing*",
            "Maximum_tree_age": "Maximum tree age",
            "Geology": "Geology",
            "Soil_type": "Soil type",
            "Woodland_association": "Woodland association",
            "Management_system": "Management system",
            "Silvicultural_system": "Silvicultural system",
            "Top_height_diameter_cm": "Top-height diameter (cm)",
            "Trees_BHD_ge_12cm": "Trees BHD ≥ 12 cm",
            "Tree_count_reference_year": "Year when BHD was measured",
            "Installation_date": "Installation date",
        }
    )

    mo.vstack(
        [
            mo.md(
                """
            ## LWF site metadata

            `*Species listing` indicates whether the WSL page explicitly
            mentions one or multiple tree species in its main-tree / age
            information; it is **not** a complete species inventory.

            `Trees BHD ≥ 12 cm` is shown together with its **reference year**.
            WSL defines top-height diameter as the quadratic average diameter
            of the 100 thickest trees per hectare.

            The WSL plot area is used as the primary area value. Lantsch is
            left missing because the WSL page reports its plot size as
            `n.d.` rather than silently substituting the DEIMS size.
            """
            ),
            site_selector,
            table,
            mo.md(
                f"**Sources:** [WSL LWF sites]({sources['WSL LWF sites']}) · "
                f"[DEIMS-SDR site search]({sources['DEIMS-SDR search']})"
            ),
        ]
    )
    return


if __name__ == "__main__":
    app.run()
