name: Strip Notebooks Output

on: [ push, pull_request ]
jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check notebooks are stripped
        uses: kynan/nbstripout@main
        with:
          paths: '**/*.ipynb'
